In [3]:
%useLatestDescriptors
%use dataframe
@file:DependsOn("com.github.doyaaaaaken:kotlin-csv-jvm:1.7.0")

import com.github.doyaaaaaken.kotlincsv.dsl.csvWriter
import io.github.oshai.kotlinlogging.KotlinLogging.logger
import kotlin.reflect.full.declaredMemberProperties

//avgClusterSize,avgClusters,avgClustersExcluded,avgClustersInPath,avgClustersIncludedCompletely,avgNodesInDeadCluster,avgPercentageBudgetUnused,avgPercentageClusterExcluded,avgPercentageClusterRevenueExcluded,avgRevenueInDeadCluster,budgetDist,budgetFactor,clustering,elimination,eliminationRevenueWeight,eliminationSparsityWeight,k,mode,r,runs,set

@DataSchema
data class OneRun(
    val avgClusterSize: Double,
    val avgClusters: Double,
    val avgClustersExcluded: Double,
    val avgClustersInPath: Double,
    val avgClustersIncludedCompletely: Double,
    val avgNodesInDeadCluster: Double,
    val avgPercentageBudgetUnused: Double,
    val avgPercentageClusterExcluded: Double,
    val avgPercentageClusterRevenueExcluded: Double,
    val avgRevenueInDeadCluster: Double,
    val budgetDist: String,
    val budgetFactor: Double,
    val clustering: String,
    val elimination: String,
    val eliminationRevenueWeight: Double,
    val eliminationSparsityWeight: Double,
    val k: Int,
    val mode: String,
    val r: Double,
    val runs: Int,
    val set: String
)

//avgClusterPercentageIncluded,avgClusterSize,avgClustersIncludedCompletely,avgNodesInDeadCluster,avgPercentageBudgetUnused,avgPercentageClusterExcluded,avgPercentageClusterRevenueExcluded,avgRevenueInDeadCluster,budgetDist,budgetFactor,clustering,elimination,eliminationRevenueWeight,eliminationSparsityWeight,k,mode,r,runs,set

data class globalRun(
    val avgClusterPercentageIncluded: Double,
    val avgClusterSize: Double,
    val avgClustersIncludedCompletely: Double,
    val avgNodesInDeadCluster: Double,
    val avgPercentageBudgetUnused: Double,
    val avgPercentageClusterExcluded: Double,
    val avgPercentageClusterRevenueExcluded: Double,
    val avgRevenueInDeadCluster: Double,
    val budgetDist: String,
    val budgetFactor: Double,
    val clustering: String,
    val elimination: String,
    val eliminationRevenueWeight: Double,
    val eliminationSparsityWeight: Double,
    val k: Int,
    val mode: String,
    val r: Double,
    val runs: Int,
    val set: String
)

val relativePath = "/op-solver-strict/results/meta/"
val pathToFolder  = java.nio.file.Paths.get(System.getProperty("user.dir"), "../../../..").normalize().toAbsolutePath()
    .toString() + relativePath


val folder = File(pathToFolder)

val csvFiles = folder.listFiles { file -> file.extension == "csv" } ?: arrayOf()
val dfs: Map<String, DataFrame<OneRun>> = csvFiles.filter { it.name != "global.csv" }.associate { file ->
    val name = file.nameWithoutExtension
    val dfRaw = DataFrame.readCsv(file)
        .convert("avgClusterSize") { it.toString().toDouble() }
        .convert("avgClusters") { it.toString().toDouble() }
        .convert("avgClustersExcluded") { it.toString().toDouble() }
        .convert("avgClustersInPath") { it.toString().toDouble() }
        .convert("avgClustersIncludedCompletely") { it.toString().toDouble() }
        .convert("avgNodesInDeadCluster") { it.toString().toDouble() }
        .convert("avgPercentageBudgetUnused") { it.toString().toDouble() }
        .convert("avgPercentageClusterExcluded") { it.toString().toDouble() }
        .convert("avgPercentageClusterRevenueExcluded") { it.toString().toDouble() }
        .convert("avgRevenueInDeadCluster") { it.toString().toDouble() }
        .convert("budgetDist") { it.toString() }
        .convert("budgetFactor") { it.toString().toDouble() }
        .convert("clustering") { it.toString() }
        .convert("elimination") { it.toString() }
        .convert("eliminationRevenueWeight") { it.toString().toDouble() }
        .convert("eliminationSparsityWeight") { it.toString().toDouble() }
        .convert("k") { it.toString().toInt() }
        .convert("mode") { it.toString() }
        .convert("r") { it.toString().toDouble() }
        .convert("runs") { it.toString().toInt() }
        .convert("set") { it.toString() }
        .cast<OneRun>()
    name to dfRaw
}

val globalFile = folder.listFiles { file -> file.name == "global.csv" }.firstOrNull()
    ?: throw IllegalStateException("Global CSV file not found")

var globalDf = DataFrame.readCsv(globalFile)
    .convert("avgClusterPercentageIncluded") { it.toString().toDouble() }
    .convert("avgClusterSize") { it.toString().toDouble() }
    .convert("avgClustersIncludedCompletely") { it.toString().toDouble() }
    .convert("avgNodesInDeadCluster") { it.toString().toDouble() }
    .convert("avgPercentageBudgetUnused") { it.toString().toDouble() }
    .convert("avgPercentageClusterExcluded") { it.toString().toDouble() }
    .convert("avgPercentageClusterRevenueExcluded") { it.toString().toDouble() }
    .convert("avgRevenueInDeadCluster") { it.toString().toDouble() }
    .convert("budgetDist") { it.toString() }
    .convert("budgetFactor") { it.toString().toDouble() }
    .convert("clustering") { it.toString() }
    .convert("elimination") { it.toString() }
    .convert("eliminationRevenueWeight") { it.toString().toDouble() }
    .convert("eliminationSparsityWeight") { it.toString().toDouble() }
    .convert("k") { it.toString().toInt() }
    .convert("mode") { it.toString() }
    .convert("r") { it.toString().toDouble() }
    .convert("runs") { it.toString().toInt() }
    .convert("set") { it.toString() }
    .cast<globalRun>()

globalDf

avgClusterPercentageIncluded,avgClusterSize,avgClustersIncludedCompletely,avgNodesInDeadCluster,avgPercentageBudgetUnused,avgPercentageClusterExcluded,avgPercentageClusterRevenueExcluded,avgRevenueInDeadCluster,budgetDist,budgetFactor,clustering,elimination,eliminationRevenueWeight,eliminationSparsityWeight,k,mode,r,runs,set
1.000000,24.800000,0.000000,0.000000,0.030000,0.400000,0.390000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base
1.000000,24.800000,0.000000,0.000000,0.020000,0.150000,0.150000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base
1.000000,24.800000,0.000000,0.000000,0.020000,0.020000,0.020000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base
1.000000,24.800000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base
1.000000,24.800000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.580000,0.580000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.430000,0.430000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.270000,0.270000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.120000,0.120000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.030000,0.030000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.620000,0.620000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,1,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.800000,1,base
1.000000,24.800000,0.010000,0.000000,0.330000,0.600000,0.590000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,1,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.150000,0.150000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,1,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.590000,0.590000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.410000,0.410000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base
1.000000,24.800000,0.000000,0.000000,0.310000,0.260000,0.260000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.120000,0.110000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.040000,0.040000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base
1.000000,24.800000,0.000000,0.000000,0.320000,0.580000,0.580000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base

In [4]:

globalDf = globalDf.filter { it.runs == 5 }
val filteredDfs: Map<String, DataFrame<OneRun>> = dfs.mapValues { (_, df) ->
    df.filter { it.runs == 5 }
}
dfs["eil101"]

avgClusterSize,avgClusters,avgClustersExcluded,avgClustersInPath,avgClustersIncludedCompletely,avgNodesInDeadCluster,avgPercentageBudgetUnused,avgPercentageClusterExcluded,avgPercentageClusterRevenueExcluded,avgRevenueInDeadCluster,budgetDist,budgetFactor,clustering,elimination,eliminationRevenueWeight,eliminationSparsityWeight,k,mode,r,runs,set
20.200000,4.000000,1.000000,4.000000,0.000000,0.000000,0.030000,0.200000,0.250000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.010000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.030000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.010000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base
20.200000,4.000000,1.000000,4.000000,0.000000,0.000000,0.330000,0.200000,0.210000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.320000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.310000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.310000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.320000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base
20.200000,3.000000,2.000000,3.000000,0.000000,0.000000,0.320000,0.400000,0.460000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,1,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.310000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.800000,1,base
20.200000,4.000000,1.000000,4.000000,0.000000,0.000000,0.310000,0.200000,0.200000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,1,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.320000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,1,base
20.200000,4.000000,1.000000,4.000000,0.000000,0.000000,0.330000,0.200000,0.200000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base
20.200000,4.000000,1.000000,4.000000,0.000000,0.000000,0.320000,0.200000,0.230000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.330000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.310000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base
20.200000,5.000000,0.000000,5.000000,0.000000,0.000000,0.320000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base
20.200000,3.000000,2.000000,3.000000,0.000000,0.000000,0.310000,0.400000,0.450000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base

In [5]:
val mergedDf = dfs.map { (name, df) ->
    df.add("name") { name }
}.concat()
mergedDf

avgClusterSize,avgClusters,avgClustersExcluded,avgClustersInPath,avgClustersIncludedCompletely,avgNodesInDeadCluster,avgPercentageBudgetUnused,avgPercentageClusterExcluded,avgPercentageClusterRevenueExcluded,avgRevenueInDeadCluster,budgetDist,budgetFactor,clustering,elimination,eliminationRevenueWeight,eliminationSparsityWeight,k,mode,r,runs,set,name
24.970000,16.000000,13.000000,16.000000,0.000000,0.000000,0.020000,0.450000,0.460000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base,u724
24.970000,26.000000,3.000000,26.000000,0.000000,0.000000,0.020000,0.100000,0.100000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base,u724
24.970000,29.000000,0.000000,29.000000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base,u724
24.970000,29.000000,0.000000,29.000000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base,u724
24.970000,29.000000,0.000000,29.000000,0.000000,0.000000,0.010000,0.000000,0.000000,0.000000,ea4opml,1.000000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base,u724
24.970000,13.000000,16.000000,13.000000,0.000000,0.000000,0.310000,0.550000,0.550000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base,u724
24.970000,16.000000,13.000000,16.000000,0.000000,0.000000,0.310000,0.450000,0.470000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base,u724
24.970000,21.000000,8.000000,21.000000,0.000000,0.000000,0.310000,0.280000,0.280000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base,u724
24.970000,27.000000,2.000000,27.000000,0.000000,0.000000,0.320000,0.070000,0.080000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base,u724
24.970000,29.000000,0.000000,29.000000,0.000000,0.000000,0.320000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base,u724
24.970000,9.000000,20.000000,9.000000,0.000000,0.000000,0.310000,0.690000,0.700000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,1,base,u724
24.970000,29.000000,0.000000,29.000000,0.000000,0.000000,0.320000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.800000,1,base,u724
24.970000,11.000000,18.000000,11.000000,1.000000,0.000000,0.320000,0.620000,0.620000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,1,base,u724
24.970000,23.000000,6.000000,23.000000,0.000000,0.000000,0.320000,0.210000,0.210000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,1,base,u724
24.970000,13.000000,16.000000,13.000000,0.000000,0.000000,0.310000,0.550000,0.520000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base,u724
24.970000,15.000000,14.000000,15.000000,0.000000,0.000000,0.310000,0.480000,0.480000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.400000,5,base,u724
24.970000,22.000000,7.000000,22.000000,0.000000,0.000000,0.310000,0.240000,0.240000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.500000,5,base,u724
24.970000,24.000000,5.000000,24.000000,0.000000,0.000000,0.320000,0.170000,0.180000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.600000,5,base,u724
24.970000,29.000000,0.000000,29.000000,0.000000,0.000000,0.330000,0.000000,0.000000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.700000,5,base,u724
24.970000,13.000000,16.000000,13.000000,0.000000,0.000000,0.310000,0.550000,0.550000,0.000000,ea4opml,0.700000,fbckmn,tsprce,0.250000,0.500000,25,random,0.300000,5,base,u724

In [6]:
val clusteringNoDiscard = listOf<String>("fbckmd", "fbckmn", "rkmd", "rkmn")
val clusteringDiscard = listOf<String>("nckmd", "nckmn")
//[d493, eil101, fl1400, gil262, lin318, pcb1173, pr2392, pr299, rd400, u574, u724]
val instancesEqual = listOf<String>("eil101", "gil262", "lin318", "pcb1173", "pr2392", "pr299", "rd400", "u574", "u724")

mergedDf.filter { it.name in instancesEqual && it.clustering in clusteringDiscard }.map { it.avgNodesInDeadCluster }.average()

NaN

In [7]:

mergedDf.filter { it.name == "fl1400" && it.clustering in clusteringDiscard }.map { it.avgNodesInDeadCluster }.average()

NaN

In [8]:
mergedDf.filter { it.name == "d493" && it.clustering in clusteringDiscard }.map { it.avgNodesInDeadCluster }.average()

NaN

In [9]:
val clusteringSplit = listOf<String>("rkmd", "rkmn")
val clusteringFlow = listOf<String>("fbckmd", "fbckmn")

mergedDf.filter { it.clustering in clusteringSplit }.map { it.avgClusterSize }.average()

NaN

In [10]:

mergedDf.filter { it.clustering in clusteringFlow }.map { it.avgClusterSize }.average()

24.34541471714094

In [11]:
mergedDf.filter { it.clustering in clusteringDiscard && it.mode == "flat" }.map { it.avgRevenueInDeadCluster }.average()

NaN

In [12]:
mergedDf.filter { it.clustering in clusteringDiscard && it.mode == "random" }.map { it.avgRevenueInDeadCluster }.average()

NaN